/*
 * Copyright (C) 2015 Yann D'Isanto
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.netbeans.modules.mongodb.indexes;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.netbeans.modules.mongodb.ui.util.ValidablePanel;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbBundle.Messages;

/**
 *
 * @author Yann D'Isanto
 */
@Messages({
    "CreateIndexPanel.fieldsLabel.text=Fields",
    "CreateIndexPanel.uniqueCheckBox.text=unique",
    "CreateIndexPanel.sparseCheckBox.text=sparse",
    "CreateIndexPanel.okButton.text=Ok",
    "CreateIndexPanel.cancelButton.text=Cancel",
    "CreateIndexPanel.nameLabel.text=Name",
    "CreateIndexPanel.addFieldButton.text=add",
    "CreateIndexPanel.removeFieldButton.text=remove",
    "createIndexText=Create Index",
    "ACTION_Create_Index=Create Index",
    "VALIDATION_emptyName=specify the index name",
    "VALIDATION_noKey=specify at least one key"
})
public class CreateIndexPanel extends ValidablePanel {

    private static final long serialVersionUID = 1L;

    private final DefaultListModel<Index.Key> keyFieldsListModel = new DefaultListModel<>();
    
    /**
     * Creates new form CreateIndexPanel
     */
    public CreateIndexPanel() {
        initComponents();
        nameField.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                performValidation();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                performValidation();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
        keyFieldsList.setCellRenderer(new IndexKeyListCellRenderer());
        keyFieldsList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        keyFieldsList.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                removeFieldButton.setEnabled(e.getFirstIndex() > -1);
            }
        });
        keyFieldsListModel.addListDataListener(new ListDataListener() {

            @Override
            public void intervalAdded(ListDataEvent e) {
                performValidation();
            }

            @Override
            public void intervalRemoved(ListDataEvent e) {
                performValidation();
            }

            @Override
            public void contentsChanged(ListDataEvent e) {
            }
        });
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                performValidation();
            }
        });
    }

    @Override
    protected String computeValidationProblem() {
        if(keyFieldsListModel.getSize() == 0) {
            return Bundle.VALIDATION_noKey();
        }
        return null;
    }

    Index getIndex() {
        String name = nameField.getText();
        return new Index(
            name.isEmpty() ? null : name,
            null,
            Collections.list(keyFieldsListModel.elements()),
            sparseCheckBox.isSelected(),
            uniqueCheckBox.isSelected()
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uniqueCheckBox = new javax.swing.JCheckBox();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        addFieldButton = new javax.swing.JButton();
        fieldsLabel = new javax.swing.JLabel();
        removeFieldButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        keyFieldsList = new javax.swing.JList<Index.Key>();
        sparseCheckBox = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(uniqueCheckBox, org.openide.util.NbBundle.getMessage(CreateIndexPanel.class, "CreateIndexPanel.uniqueCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(CreateIndexPanel.class, "CreateIndexPanel.nameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(addFieldButton, org.openide.util.NbBundle.getMessage(CreateIndexPanel.class, "CreateIndexPanel.addFieldButton.text")); // NOI18N
        addFieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFieldButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(fieldsLabel, org.openide.util.NbBundle.getMessage(CreateIndexPanel.class, "CreateIndexPanel.fieldsLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(removeFieldButton, org.openide.util.NbBundle.getMessage(CreateIndexPanel.class, "CreateIndexPanel.removeFieldButton.text")); // NOI18N
        removeFieldButton.setEnabled(false);
        removeFieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFieldButtonActionPerformed(evt);
            }
        });

        keyFieldsList.setModel(keyFieldsListModel);
        jScrollPane2.setViewportView(keyFieldsList);

        org.openide.awt.Mnemonics.setLocalizedText(sparseCheckBox, org.openide.util.NbBundle.getMessage(CreateIndexPanel.class, "CreateIndexPanel.sparseCheckBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addFieldButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeFieldButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sparseCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uniqueCheckBox, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sparseCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uniqueCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldsLabel)
                    .addComponent(removeFieldButton)
                    .addComponent(addFieldButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFieldButtonActionPerformed
         Enumeration<Index.Key> keys = keyFieldsListModel.elements();
         List<String> usedKeys = new ArrayList<>();
         while(keys.hasMoreElements()) {
             usedKeys.add(keys.nextElement().getField());
         }
         Index.Key key = IndexKeyPanel.showCreateDialog(usedKeys);
         if(key != null) {
             keyFieldsListModel.addElement(key);
         }
    }//GEN-LAST:event_addFieldButtonActionPerformed

    private void removeFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFieldButtonActionPerformed
        keyFieldsListModel.removeElementAt(keyFieldsList.getSelectedIndex());
    }//GEN-LAST:event_removeFieldButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFieldButton;
    private javax.swing.JLabel fieldsLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Index.Key> keyFieldsList;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton removeFieldButton;
    private javax.swing.JCheckBox sparseCheckBox;
    private javax.swing.JCheckBox uniqueCheckBox;
    // End of variables declaration//GEN-END:variables

    public static Index showDialog() {
        final CreateIndexPanel panel = new CreateIndexPanel();
        final DialogDescriptor desc = new DialogDescriptor(panel, Bundle.IndexKeyPanel_title());
        panel.setNotificationLineSupport(desc.createNotificationLineSupport());
        panel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                desc.setValid(panel.isValidationSuccess());
            }
        });
        if (NotifyDescriptor.OK_OPTION.equals(DialogDisplayer.getDefault().notify(desc))) {
            return panel.getIndex();
        }
        return null;
    }
}
