/*
 * Copyright (C) 2015 Yann D'Isanto
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.netbeans.modules.mongodb.indexes;

import org.netbeans.modules.mongodb.indexes.Index.Geo2DSphereOptions;

/**
 *
 * @author Yann D'Isanto
 */
public class Geo2DSphereOptionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Geo2DSphereOptionsPanel
     */
    public Geo2DSphereOptionsPanel() {
        initComponents();
    }

    public Geo2DSphereOptions getGeo2DSphereOptions() {
        Integer indexVersion = indexVersionCheckBox.isSelected() ? (Integer) indexVersionSpinner.getValue() : null;
        return new Geo2DSphereOptions(indexVersion);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indexVersionCheckBox = new javax.swing.JCheckBox();
        indexVersionSpinner = new javax.swing.JSpinner();

        org.openide.awt.Mnemonics.setLocalizedText(indexVersionCheckBox, org.openide.util.NbBundle.getMessage(Geo2DSphereOptionsPanel.class, "Geo2DSphereOptionsPanel.indexVersionCheckBox.text")); // NOI18N
        indexVersionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexVersionCheckBoxActionPerformed(evt);
            }
        });

        indexVersionSpinner.setModel(new javax.swing.SpinnerNumberModel(2, 1, 2, 1));
        indexVersionSpinner.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indexVersionCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indexVersionSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indexVersionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexVersionCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void indexVersionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexVersionCheckBoxActionPerformed
        indexVersionSpinner.setEnabled(indexVersionCheckBox.isSelected());
    }//GEN-LAST:event_indexVersionCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox indexVersionCheckBox;
    private javax.swing.JSpinner indexVersionSpinner;
    // End of variables declaration//GEN-END:variables
}
