/* 
 * Copyright (C) 2015 Yann D'Isanto
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
@Messages({
    "CollectionNode.avgObjSize.name=Avg Object Size",
    "CollectionNode.avgObjSize.displayname=Avg Object Size",
    "CollectionNode.avgObjSize.shortdesc=Average object size in bytes",
    "CollectionNode.capped.name=Capped",
    "CollectionNode.capped.displayname=Capped",
    "CollectionNode.capped.shortdesc=Shows whether or not this collection is capped",
    "CollectionNode.count.name=Count",
    "CollectionNode.count.displayname=Count",
    "CollectionNode.count.shortdesc=Number of documents",
    "CollectionNode.lastExtentSize.name=Last Extent Size",
    "CollectionNode.lastExtentSize.displayname=Last Extent Size",
    "CollectionNode.lastExtentSize.shortdesc=size of the most recently created extent in bytes",
    "CollectionNode.nindexes.name=Number Of Indexes",
    "CollectionNode.nindexes.displayname=Number Of Indexes",
    "CollectionNode.nindexes.shortdesc=Number of indexes",
    "CollectionNode.ns.name=Namespace",
    "CollectionNode.ns.displayname=Namespace",
    "CollectionNode.ns.shortdesc=Namespace",
    "CollectionNode.numExtents.name=Number Of Extents",
    "CollectionNode.numExtents.displayname=Number Of Extents",
    "CollectionNode.numExtents.shortdesc=Number of extents (contiguously allocated chunks of datafile space)",
    "CollectionNode.ok.name=OK",
    "CollectionNode.ok.displayname=OK",
    "CollectionNode.ok.shortdesc=OK",
    "CollectionNode.paddingFactor.name=Padding Factor",
    "CollectionNode.paddingFactor.displayname=Padding Factor",
    "CollectionNode.paddingFactor.shortdesc=Padding can speed up updates if documents grow",
    "CollectionNode.serverUsed.name=Server Used",
    "CollectionNode.serverUsed.displayname=Server Used",
    "CollectionNode.serverUsed.shortdesc=Server Used",
    "CollectionNode.size.name=Size",
    "CollectionNode.size.displayname=Size",
    "CollectionNode.size.shortdesc=Collection size in bytes",
    "CollectionNode.storageSize.name=Storage Size",
    "CollectionNode.storageSize.displayname=Storage Size",
    "CollectionNode.storageSize.shortdesc=(Pre)allocated space in bytes",
    "CollectionNode.systemFlags.name=System Flags",
    "CollectionNode.systemFlags.displayname=System Flags",
    "CollectionNode.systemFlags.shortdesc=System Flags",
    "CollectionNode.totalIndexSize.name=Total Index Size",
    "CollectionNode.totalIndexSize.displayname=Total Index Size",
    "CollectionNode.totalIndexSize.shortdesc=total index size in bytes",
    "CollectionNode.userFlags.name=User Flags",
    "CollectionNode.userFlags.displayname=User Flags",
    "CollectionNode.userFlags.shortdesc=User Flags",
    "DBNode.avgObjSize.name=Avg Object Size",
    "DBNode.avgObjSize.displayname=Avg Object Size",
    "DBNode.avgObjSize.shortdesc=The average size of each document in bytes.",
    "DBNode.collections.name=Collections",
    "DBNode.collections.displayname=Collections",
    "DBNode.collections.shortdesc=The number of collections in that database.",
    "DBNode.dataFileVersion.name=Data File Version",
    "DBNode.dataFileVersion.displayname=Data File Version",
    "DBNode.dataFileVersion.shortdesc=Data File Version",
    "DBNode.dataSize.name=Data Size",
    "DBNode.dataSize.displayname=Data Size",
    "DBNode.dataSize.shortdesc=The total size in bytes of the data held in this database including the padding factor.",
    "DBNode.db.name=DB",
    "DBNode.db.displayname=DB",
    "DBNode.db.shortdesc=Database",
    "DBNode.extentFreeList_num.name=Extents Number",
    "DBNode.extentFreeList_num.displayname=Extents Number",
    "DBNode.extentFreeList_num.shortdesc=Number of extents in the freelist. Only present when using the mmapv1 storage engine.",
    "DBNode.extentFreeList_size.name=Extents Total Size",
    "DBNode.extentFreeList_size.displayname=Extents Total Size",
    "DBNode.extentFreeList_size.shortdesc=Total size of the extents on the freelist. The scale argument affects this value. Only present when using the mmapv1 storage engine.",
    "DBNode.fileSize.name=File Size",
    "DBNode.fileSize.displayname=File Size",
    "DBNode.fileSize.shortdesc=The total size in bytes of the data files that hold the database.",
    "DBNode.indexes.name=Indexes",
    "DBNode.indexes.displayname=Indexes",
    "DBNode.indexes.shortdesc=Contains a count of the total number of indexes across all collections in the database.",
    "DBNode.indexSize.name=Index Size",
    "DBNode.indexSize.displayname=Index Size",
    "DBNode.indexSize.shortdesc=The total size in bytes of all indexes created on this database.",
    "DBNode.objects.name=Objects",
    "DBNode.objects.displayname=Objects",
    "DBNode.objects.shortdesc=The number of objects in the database across all collections.",
    "DBNode.ok.name=OK",
    "DBNode.ok.displayname=OK",
    "DBNode.ok.shortdesc=OK",
    "DBNode.nsSizeMB.name=NS Size MB",
    "DBNode.nsSizeMB.displayname=NS Size MB",
    "DBNode.nsSizeMB.shortdesc=The total size of the namespace files (i.e. that end with .ns) for this database.",
    "DBNode.numExtents.name=Number of extents",
    "DBNode.numExtents.displayname=Number of extents",
    "DBNode.numExtents.shortdesc=Contains a count of the number of extents in the database across all collections.",
    "DBNode.serverUsed.name=Server Used",
    "DBNode.serverUsed.displayname=Server Used",
    "DBNode.serverUsed.shortdesc=Server Used",
    "DBNode.storageSize.name=Storage Size",
    "DBNode.storageSize.displayname=Storage Size",
    "DBNode.storageSize.shortdesc=The total amount of space in bytes allocated to collections in this database for document storage.",
    "IndexNode.dropDuplicates.name=Drop duplicates",
    "IndexNode.dropDuplicates.displayname=Drop duplicates",
    "IndexNode.dropDuplicates.shortdesc=Index drop duplicates flag",
    "IndexNode.name.name=Name",
    "IndexNode.name.displayname=Name",
    "IndexNode.name.shortdesc=Index name",
    "IndexNode.nameSpace.name=Namespace",
    "IndexNode.nameSpace.displayname=Namespace",
    "IndexNode.nameSpace.shortdesc=Index namespace",
    "IndexNode.sparse.name=Sparse",
    "IndexNode.sparse.displayname=Sparse",
    "IndexNode.sparse.shortdesc=Index sparse flag",
    "IndexNode.unique.name=Unique",
    "IndexNode.unique.displayname=Unique",
    "IndexNode.unique.shortdesc=Index unique flag",
    "IndexNode.expireAfterSeconds.name=Expire After Seconds",
    "IndexNode.expireAfterSeconds.displayname=Expire after seconds",
    "IndexNode.expireAfterSeconds.shortdesc=Index document TTL in seconds",
    "IndexNode.indexVersion.name=Index version",
    "IndexNode.indexVersion.displayname=Index version",
    "IndexNode.indexVersion.shortdesc=Index version",
    "IndexNode.storageEngine.name=Storage engine",
    "IndexNode.storageEngine.displayname=Storage engine",
    "IndexNode.storageEngine.shortdesc=Storage engine",
    "IndexNode.weights.name=Weights",
    "IndexNode.weights.displayname=Weights",
    "IndexNode.weights.shortdesc=Weights",
    "IndexNode.defaultLanguage.name=Default language",
    "IndexNode.defaultLanguage.displayname=Default language",
    "IndexNode.defaultLanguage.shortdesc=Default language",
    "IndexNode.languageOverride.name=Language",
    "IndexNode.languageOverride.displayname=Language",
    "IndexNode.languageOverride.shortdesc=Language",
    "IndexNode.textVersion.name=Text index version",
    "IndexNode.textVersion.displayname=Text index version",
    "IndexNode.textVersion.shortdesc=Text index version",
    "IndexNode.bits.name=Bits",
    "IndexNode.bits.displayname=Bits",
    "IndexNode.bits.shortdesc=Bits",
    "IndexNode.min.name=Min",
    "IndexNode.min.displayname=Min",
    "IndexNode.min.shortdesc=Min",
    "IndexNode.max.name=Max",
    "IndexNode.max.displayname=Max",
    "IndexNode.max.shortdesc=Max",
    "IndexNode.2dsphereVersion.name=2D sphere index version",
    "IndexNode.2dsphereVersion.displayname=2D sphere index version",
    "IndexNode.2dsphereVersion.shortdesc=2D sphere index version",
    "IndexNode.bucketSize.name=Bucket size",
    "IndexNode.bucketSize.displayname=Bucket size",
    "IndexNode.bucketSize.shortdesc=Bucket size",
    "IndexKeyNode.field.name=Key field",
    "IndexKeyNode.field.displayname=Key field",
    "IndexKeyNode.field.shortdesc=Index key field name",
    "IndexKeyNode.sort.name=Sort",
    "IndexKeyNode.sort.displayname=Sort",
    "IndexKeyNode.sort.shortdesc=Index key field sort"
})
package org.netbeans.modules.mongodb.ui.explorer;

import org.openide.util.NbBundle.Messages;
